### ISSUE TITLE
Not compatible with Laravel 4.1

### ISSUE THREAD

**Issue by kenske** [jonphipps/laravel4-idehelper-generator#9]
Is it just a matter of updating composer.json?

**Comment by cskiwi** [comment]
Is this going to be fixed?

**Comment by jonphipps** [comment]
Sorry for the lack of attention to this. A couple of months ago I updated the readme:
"It may be obvious from the lack of commits, but I'm not maintaining this at the moment. I would suggest that you use barryvdh/laravel-ide-helper instead, since it basically does the same thing, although with slightly different results."

So the answer to "Is this going to be fixed?" is that I don't have time right now, and right at the moment I'm not using Laravel 4.1, but... if there's something that you prefer about the way I implemented this rather than the one created by barryvdh then let me know and I'll see what I can do when I get back to Laravel in a month or so.

I just do have a better answer than that since I'm pretty swamped right now.
